### ISSUE TITLE
Incomplete identifiers and bad `next` URI in AnnotationPages?

### ISSUE THREAD

**Issue by jbaiter** [nationalarchives/miiify#16]
Take this annotation page referenced from the manifest at https://miiify.rocks/manifest/diamond_jubilee_of_the_metro:

https://miiify.rocks/annotations/diamond_jubilee_of_the_metro?page=0&target=https%3A//miiifystore.s3.eu-west-2.amazonaws.com/diamond_jubilee_of_the_metro/c/3/23b48727-680c-4562-9f6c-c5dc4f75b449%23xywh%3D431%2C429%2C895%2C330

Its `id` is https://miiify.rocks/annotations/diamond_jubilee_of_the_metro?page=0

Looking at another annotation page from the same canvas, but with a different target:
https://miiify.rocks/annotations/diamond_jubilee_of_the_metro?page=0&target=https%3A//miiifystore.s3.eu-west-2.amazonaws.com/diamond_jubilee_of_the_metro/c/3/23b48727-680c-4562-9f6c-c5dc4f75b449%23xywh%3D437%2C1406%2C898%2C305

The `id` is identical to the first annotation. This is likely to cause problems for client applications that use the identifier from the dereferenced resource. The easy fix would probably be to include the `target` request parameter in the `id`.

Another issue with the annotations is that the `next` key is also identical for both annotations, in both cases it's https://miiify.rocks/annotations/diamond_jubilee_of_the_metro?page=1, which contains all of the annotations of the complete manifest. I'd argue that the `next` key should not even be included, since the way annotation pages are used in this manifest, one page only ever contains a single annotation (the one targeting the resource from the `target` request parameter). Or am I misunderstanding something? In the application I'm currently working on this causes a large amount of requests, since it naively follows the `next` links and thus fetches the complete set of annotations multiple times, once for each annotation page referenced from the manifest.

**Comment by jptmoore** [comment]
Thanks for raising this @jbaiter I am back working on this code so will look at fixing this.

**Comment by jptmoore** [comment]
Hi @jbaiter I have addressed the target param issue I hope in this branch https://github.com/nationalarchives/miiify/tree/breaking/v1 and made performance improvements including a new backend storage format called 'pack' if you want to scale more than git. It is a breaking change for the current git storage format though.

**Comment by jptmoore** [comment]
I have merged that branch to main now. If you would like to experiment with the server online you can use https://miiify.onrender.com/ which will spin up/down so can take about 10 seconds to come alive.
